=== AugusLcz/xmlTD/td2/td2Film.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"

           elementFormDefault="qualified">
    <xs:element name="FILMS">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="FILM"/>
                <xs:element ref="ARTISTE"/>

            </xs:choice>
        </xs:complexType>
        <xs:keyref name="idRole" refer="idArt">
            <xs:selector xpath="FILM/ROLES/ROLE"/>
            <xs:field xpath="@idRole"/>
        </xs:keyref>

        <xs:key name="idArt">
            <xs:selector xpath="ARTISTE"/>
            <xs:field xpath="@id"/>
        </xs:key>
    </xs:element>
    <xs:element name="FILM">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="TITRE"/>
                <xs:element ref="GENRE"/>
                <xs:element ref="PAYS"/>
                <xs:element ref="MES"/>
                <xs:element ref="ROLES"/>
                <xs:element ref="RESUME"/>
            </xs:sequence>
            <xs:attribute name="Annee" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="TITRE" type="xs:string"/>
    <xs:element name="GENRE" type="xs:string"/>
    <xs:element name="PAYS" type="xs:string"/>
    <xs:element name="MES">

          <xs:complexType>
              <xs:attribute name="id" use="required"/>
          </xs:complexType>

    </xs:element>
    <xs:element name="ROLES">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ROLE"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="ROLE">
        <xs:complexType>
            <xs:attribute name="idRole" use="required"/>
        </xs:complexType>

    </xs:element>

    <xs:element name="PRENOM" type="xs:string"/>
    <xs:element name="NOM" type="xs:string"/>
    <xs:element name="INTITULE" type="xs:string"/>
    <xs:element name="RESUME" type="xs:string"/>
    <xs:element name="ARTISTE">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ACTNOM"/>
                <xs:element ref="ACTPNOM"/>
                <xs:element ref="ANNEENAISS"/>
            </xs:sequence>
            <xs:attribute name="id" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="ACTNOM" type="xs:string"/>
    <xs:element name="ACTPNOM" type="xs:string"/>
    <xs:element name="ANNEENAISS" type="xs:string"/>

</xs:schema>

=== AugusLcz/xmlTD/td2/Film1.xml
<?xml version="1.0" encoding="UTF-8"?>


<FILMS

        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="td2Film.xsd">

  <FILM Annee="">
    <TITRE></TITRE>
    <GENRE></GENRE>
    <PAYS></PAYS>
    <MES id="12"/>
    <ROLES>
      <ROLE idRole="13231"/>
      
    </ROLES>
    <RESUME></RESUME>
  </FILM>


  <ARTISTE id="3">
    <ACTNOM></ACTNOM>
    <ACTPNOM></ACTPNOM>
    <ANNEENAISS></ANNEENAISS>
  </ARTISTE>
  <ARTISTE id="12332">
    <ACTNOM></ACTNOM>
    <ACTPNOM></ACTPNOM>
    <ANNEENAISS></ANNEENAISS>
  </ARTISTE>
</FILMS>
